<a href="https://colab.research.google.com/github/lui0slpk/Arreglos_12_08_2025/blob/main/vectores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Los vectores son reserva de memoria para almacenar información, solo puede ser de un tipo, si es numérico, si es texto, debe continuar siendo texto, esto aplica para las matrices.
Los arreglos son identificadores estaticos, esto significa que es otra forma de definir, variables y constantes.

In [ ]:
import numpy as np
import os

vector = np.array([1,2,3,4,5])
print(vector)

print(vector[2])

"""Los vectores no son como las listas, no tienen un método append() para agregar elementos no tienen un método pop() para eliminar elementos, pero sí tienen método reshape() para cambiar su forma, adicionalmente después creado no se puede cambiar el tamaño del vector"""

vector1 = np.zeros(5)
print(vector1)
vector2 = np.ones(5)
print(vector2)
vector3 = np.arange(1,10)
print("rango ", vector3)
vector4 = np.linspace(1,5,10)
print(vector4)
vector5 = np.random.rand(10)
print("ramdom ",vector5)
vector6 = np.random.randint(1,10,10)
print("randint",vector6)


[1 2 3 4 5]
3
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
rango  [1 2 3 4 5 6 7 8 9]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
ramdom  [0.39814942 0.02078757 0.61019977 0.23494685 0.6793804  0.25313915
 0.86002427 0.24670628 0.48273421 0.81307864]
randint [4 5 5 5 6 7 1 4 5 1]


In [2]:
import numpy as np
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])
suma = vector1 + vector2
print("suma de vectores: ", suma)

producto = vector1 * vector2
print("Producto de vectores: ", producto)

division = vector1 / vector2
print("División de vectores: ", division)

resta = vector1 - vector2
print("Resta de vectores: ", resta)

potencia = vector1 ** 2
print("Potencia de vectores: ", potencia)



suma de vectores:  [5 7 9]
Producto de vectores:  [ 4 10 18]
División de vectores:  [0.25 0.4  0.5 ]
Resta de vectores:  [-3 -3 -3]
Potencia de vectores:  [1 4 9]


In [3]:
import numpy as np

matriz = np.random.randint(0, 100, (3,3))  # números aleatorios de 0 a 100 con una matriz de 3x3
print(matriz)

matriz2 = np.random.Generator(np.random.PCG64()).integers(0,100, (3,3))
print(matriz2)

matriz_identidad = np.eye(3)
print("\033[31m", matriz_identidad, "\033[0m")

print("\033[30m","-------------------------------------------------------------", "\033[0m")
# transponer

matriz_transpuesta = matriz.T

print("\033[33m", matriz_transpuesta, "\033[0m")

matriz_zeros= np.zeros((2, 2))
print("\033[32m", matriz_zeros, "\033[0m")
print("\033[31m", "----------llenar la diagonal de 1-----------------","\033[0m")

for  incrementador in range(2):
    matriz_zeros[incrementador][incrementador] = 1
print("\033[34m", matriz_zeros, "\033[0m")

for fila in range(2):
    for columna in range(2):
        matriz_zeros[fila][columna] = np.random.randint(0, 10)
print("\033[35m", matriz_zeros, "\033[30m")



[[ 0 61 35]
 [60 17 12]
 [24 30 54]]
[[96 20 14]
 [57 97 52]
 [66 85 23]]
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
 ------------------------------------------------------------- 
 [[ 0 60 24]
 [61 17 30]
 [35 12 54]] 
 [[0. 0.]
 [0. 0.]] 
 ----------llenar la diagonal de 1----------------- 
 [[1. 0.]
 [0. 1.]] 
 [[4. 2.]
 [2. 6.]] 
